set_trans = {
	'2ED' : 'Unlimited Edition',
	'3ED' : 'Revised Edition',
	'4ED' : 'Fourth Edition',
	'5DN' : 'Fifth Dawn',
	'5ED' : 'Fifth Edition',
	'6ED' : 'Classic Sixth Edition',
	'7ED' : 'Seventh Edition',
	'8ED' : 'Eighth Edition',
	'10E' : 'Tenth Edition',
	'ALL' : 'Alliances',
	'APC' : 'Apocalypse',
	'ARB' : 'Alara Reborn',
	'ARN' : 'Arabian Nights',
	'ATH' : 'Anthologies',
	'ATQ' : 'Antiquities',
	'ARC' : 'Archenemy',
	'AVR' : 'Avacyn Restored',
	'BOK' : 'Betrayers of Kamigawa',
	'BRB' : 'Battle Royale Box Set',
	'BTD' : 'Beatdown Box Set',
	'CHK' : 'Champions of Kamigawa',
	'CHR' : 'Chronicles',
	'CMA' : "Commander's Arsenal",
	'CON' : 'Conflux',
	'CSP' : 'Coldsnap',
	'DKA' : 'Dark Ascension',
	'DST' : 'Darksteel',
	'DIS' : 'Dissension',
	'DKM' : 'Deckmasters',
	'DGM' : "Dragon's Maze",
	'DRK' : 'The Dark',
	'DVD' : 'Duel Decks: Divine vs. Demonic',
	'DDF' : 'Duel Decks: Elspeth vs. Tezzeret',
	'DDG' : 'Duel Decks: Knights vs. Dragons',
	'DDH' : 'Duel Decks: Ajani vs. Nicol Bolas',
	'DDI' : 'Duel Decks: Venser vs. Koth',
	'DDJ' : 'Duel Decks: Izzet vs. Golgari',
	'EVG' : 'Duel Decks: Elves vs. Goblins',
	'GVL' : 'Duel Decks: Garruk vs. Liliana',
	'JVC' : 'Duel Decks: Jace vs. Chandra',
	'PVC' : 'Duel Decks: Phyrexia vs. the Coalition',
	'EVE' : 'Eventide',
	'EXO' : 'Exodus',
	'FEM' : 'Fallen Empires',
	'FUT' : 'Future Sight',
	'FVD' : 'From the Vault: Dragons',
	'FVE' : 'From the Vault: Exiled',
	'FVR' : 'From the Vault: Relics',
	'GTC' : 'Gatecrash',
	'GPT' : 'Guildpact',
	'HML' : 'Homelands',
	'HOP' : 'Planechase',
	'PC2' : 'Planechase 2012 Edition',
	'ICE' : 'Ice Age',
	'ISD' : 'Innistrad',
	'INV' : 'Invasion',
	'JUD' : 'Judgment',
	'LEA' : 'Limited Edition Alpha',
	'LEB' : 'Limited Edition Beta',
	'LEG' : 'Legends',
	'LGN' : 'Legions',
	'LRW' : 'Lorwyn',
	'M10' : 'Magic 2010',
	'M11' : 'Magic 2011',
	'M12' : 'Magic 2012',
	'M13' : 'Magic 2013',
	'CMD' : 'Magic: The Gathering-Commander',
	'ME2' : 'Masters Edition II',
	'ME3' : 'Masters Edition III',
	'ME4' : 'Masters Edition IV',
	'MED' : 'Masters Edition',
	'MIR' : 'Mirage',
	'MMQ' : 'Mercadian Masques',
	'MOR' : 'Morningtide',
	'MRD' : 'Mirrodin',
	'MBS' : 'Mirrodin Besieged',
	'VGO' : 'MTGO Vanguard',
	'NPH' : 'New Phyrexia',
	'9ED' : 'Ninth Edition',
	'NMS' : 'Nemesis',
	'ODY' : 'Odyssey',
	'ONS' : 'Onslaught',
	'PO2' : 'Portal Second Age',
	'PCY' : 'Prophecy',
	'PLC' : 'Planar Chaos',
	'PLS' : 'Planeshift',
	'POR' : 'Portal',
	'PTK' : 'Portal Three Kingdoms',
	'PD2' : 'Premium Deck Series: Fire and Lightning',
	'PD3' : 'Premium Deck Series: Graveborn',
	'PDS' : 'Premium Deck Series: Slivers',
	'PRM' : 'Promotional',
	'H09' : 'Premium Deck Series: Slivers',
	'RAV' : 'Ravnica: City of Guilds',
	'RTR' : 'Return to Ravnica',
	'ROE' : 'Rise of the Eldrazi',
	'SOM' : 'Scars of Mirrodin',
	'SCG' : 'Scourge',
	'SHM' : 'Shadowmoor',
	'SVT' : 'Duel Decks: Sorin vs. Tibalt',
	'ALA' : 'Shards of Alara',
	'SOK' : 'Saviors of Kamigawa',
	'S00' : 'Starter 2000',
	'S99' : 'Starter 1999',
	'STH' : 'Stronghold',
	'TMP' : 'Tempest',
	'TE' : 'Tempest',
	'TOR' : 'Torment',
	'TSP' : 'Time Spiral',
	'TSB' : 'Time Spiral "Timeshifted"',
	'UGL' : 'Unglued',
	'UNH' : 'Unhinged',
	'UDS' : "Urza's Destiny",
	'ULG' : "Urza's Legacy",
	'USG' : "Urza's Saga",
	'VG1' : 'Vanguard Set 1',
	'VG2' : 'Vanguard Set 2',
	'VG3' : 'Vanguard Set 3',
	'VG4' : 'Vanguard Set 4',
	'V11' : 'From the Vault: Legends',
	'V12' : 'From the Vault: Realms',
	'VIS' : 'Visions',
	'WTH' : 'Weatherlight',
	'WWK' : 'Worldwake',
	'ZEN' : 'Zendikar'
}